// <auto-generated />
using CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240418043826_AddSinhVienData")]
    partial class AddSinhVienData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");

                    b.HasData(
                        new
                        {
                            MaKhoa = 1,
                            TenKhoa = "CNS"
                        },
                        new
                        {
                            MaKhoa = 2,
                            TenKhoa = "SPKT"
                        },
                        new
                        {
                            MaKhoa = 3,
                            TenKhoa = "CK"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.ToTable("Lops");

                    b.HasData(
                        new
                        {
                            MaLop = 1,
                            TenLop = "21T3"
                        },
                        new
                        {
                            MaLop = 2,
                            TenLop = "21T2"
                        },
                        new
                        {
                            MaLop = 3,
                            TenLop = "22T3"
                        },
                        new
                        {
                            MaLop = 4,
                            TenLop = "22T2"
                        });
                });

            modelBuilder.Entity("DefaultNamespace.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSinhVien"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhoaMaKhoa")
                        .HasColumnType("int");

                    b.Property<int>("LopMaLop")
                        .HasColumnType("int");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("KhoaMaKhoa");

                    b.HasIndex("LopMaLop");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            MaSinhVien = 1,
                            Age = 19,
                            HoTen = "Tran Van A",
                            KhoaMaKhoa = 1,
                            LopMaLop = 1
                        },
                        new
                        {
                            MaSinhVien = 2,
                            Age = 20,
                            HoTen = "Nguyen Van B",
                            KhoaMaKhoa = 1,
                            LopMaLop = 2
                        },
                        new
                        {
                            MaSinhVien = 3,
                            Age = 21,
                            HoTen = "Le Van C",
                            KhoaMaKhoa = 1,
                            LopMaLop = 1
                        },
                        new
                        {
                            MaSinhVien = 4,
                            Age = 22,
                            HoTen = "Ho Thi D",
                            KhoaMaKhoa = 2,
                            LopMaLop = 2
                        },
                        new
                        {
                            MaSinhVien = 5,
                            Age = 23,
                            HoTen = "Duong Van E",
                            KhoaMaKhoa = 2,
                            LopMaLop = 2
                        });
                });

            modelBuilder.Entity("DefaultNamespace.SinhVien", b =>
                {
                    b.HasOne("CodeFirst.Models.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("KhoaMaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.Lop", "Lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("LopMaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("CodeFirst.Models.Khoa", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("CodeFirst.Models.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
